version: '3'

services:
  frontend:
    image: lokalhelfer_frontend
    build: ./frontend
    ports:
      - 3000:3000

  strapi:
    image: lokalhelfer_strapi
    build: ./strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
    ports:
      - 1337:1337
    depends_on:
      - db

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
